name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload Build Fail Artifacts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: build-fail-artifact
        path: ${{ github.workspace }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Upload Test Fail Artifacts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-fail-artifact
        path: ${{ github.workspace }}


    - name: Publish MaxLib.Ini NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: MaxLib.Ini/MaxLib.Ini.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: MaxLib.Ini
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.NUGET_PUSH_KEY }}
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH:
        VERSION_FILE_PATH: MaxLib.Ini/MaxLib.Ini.csproj.include
